[project]
name = 'Cosmic-Energy-Grid-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dark-energy-integration]
path = 'contracts/dark-energy-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.galactic-energy-node-registration]
path = 'contracts/galactic-energy-node-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.interstellar-power-routing]
path = 'contracts/interstellar-power-routing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
